### ISSUE TITLE
RFE: Allow code refs as values in hash passed to params_validate

### ISSUE THREAD

**Issue by djerius** [polettix/App-Easer#3]
Hi,

I'd like to use an alternate parameter validation package, e.g. Type::Params rather than Params::Validate.

I could use the commit hook to do so, but I'd need to re-implement the `args` and `config` functionality that's provided via `params_validate`, and in any case it just seems like the wrong place to put it.

If the values in the hash passed to `params_validate` were allowed to be coderefs, that would open up the possibility of using any validation mechanism.

The other change that would be useful, but may not fit into your philosophy on handling parameters, is to allow the validation code to alter the values passed to it.  Validation and normalization of input values often go together.

Thanks,
Diab

**Comment by polettix** [comment]
The need is sound and it's actually backwards-compatible. I left it out thinking about overriding `validate` in a sub-class, but of course the aim of the module is to support pure-hash interface as well so it should be there. I have some working code already, I have to add a few tests before releasing.

Regarding the validation code altering the values, the sub reference will be called with a reference to the object as the only parameter, so it can do whatever it deems necessary. My "philosophy" is to give rope when possible :grin:.

*Keep in mind* that the `validate` phase is called after the `commit` phase, because I want to adjust parameters *before* calling Params::Validate. In case you want to coalesce the two things into `validate`, you will probably want to avoid `commit` completely or be aware about the values you will find at that stage.

I'm also thinking about another hook *after* validation but before handing over to the next sub-command or to `execute`, something like `complete` or `enable`. *That* would be the right spot for an intermediate command to put actions that have to be *always* executed (e.g. creating directories, etc.)

**Comment by djerius** [comment]
> I left it out thinking about overriding `validate` in a sub-class, but of course the aim of the module is to support pure-hash interface as well so it should be there.

My first thought was to subclass as well, but `App::Easer::V2::Command` is hardwired into the code in a couple of places (`App::Easer::V2::run`, `App::Easer::V2::import`); without the possibility of changing that, I couldn't come up with a method of subclassing that would work.

One workaround would be to provide a `-commandclass` argument to `import`, use that when handling the `-inherit` and `-register` arguments, and export a bespoke `run` subroutine which uses the `-commandclass` argument to set `$class`.

> My "philosophy" is to give rope when possible.

😸👍

**Comment by polettix** [comment]
> > I left it out thinking about overriding `validate` in a sub-class, but of course the aim of the module is to support pure-hash interface as well so it should be there.
> 
> My first thought was to subclass as well, but `App::Easer::V2::Command` is hardwired into the code in a couple of places (`App::Easer::V2::run`, `App::Easer::V2::import`); without the possibility of changing that, I couldn't come up with a method of subclassing that would work.

This hurts me as the developer, because it's a spectacular failure of communication :grin:

There are possibly too many ways to subclass in ways that work, again because of providing a way to balance between hash-based definitions and full classes.

The subclassing *shifted on the hash side* can be seen in `tudu2` (e.g. [here](https://metacpan.org/release/POLETTIX/App-Easer-2.002/source/eg/tudu2)). The `use App::Easer::V2 -command ...` incantation makes the package a subclass of `App::Easer::V2::Command`, which happens both for class `TuDu` and `TuDu::Command` (both in the same file, by the way). The latter is set as the `hash_class` ([line 44](https://metacpan.org/release/POLETTIX/App-Easer-2.002/source/eg/tudu2#L44)) which means: whatever child I declare below as a hash reference, please instantiate through that class. You see this inside `inflate_children` (e.g. [here](https://github.com/polettix/App-Easer/blob/main/lib/App/Easer/V2.pm#L574)).

So, at the end of the day, [this](https://metacpan.org/release/POLETTIX/App-Easer-2.002/source/eg/lib/MuDu/Command/Add.pm) just works and every method you see there is an overriding of the relevant method in `::Command`.

On the other side of the spectrum, every sub-command might just be a class on itself and the whole hierarchy can be deduced automatically. In this case I would suggest to set a prefix ([see here](https://metacpan.org/release/POLETTIX/App-Easer-2.002/view/lib/App/Easer/V2.pm#children_prefixes)) so that you can keep around support classes/packages without risking to promote them to sub-commands. Each sub-command would then import with `-command`, like this:

```perl
package MyApp::CmdFoo::CmdBar;
use App::Easer::V2 -command => -spec => {
    help => q{Hello, I'm called as app foo bar},
    aliases => [qw< bar Bar BAR BAAAAAAR >],
    options => [
        { getopt => 'baz|b=s', default => 'galook' },
    ]
};
sub description ($self) { q{'nuff said} }
sub validate ($self) { ... }
sub execute ($self) { ... }
1;
```

Again you can strike your balance between hash-based stuff and overriding-based stuff (in the example above, `help` is in the hash specification, while `description` is a method... you can decide according to your preferences). I use the hash for static stuff like help, description, options, etc. and use overriding for things that require some real logic.

> > My "philosophy" is to give rope when possible.
> 
> 😸👍

That's about another couple of meters I guess...

**Comment by polettix** [comment]
Version 2.003 should be hitting CPAN any time now. Please let me know if validation is up to the expectations or if I missed anything.

I'll then think about adding more docs and a `complete`/`enable` hook to run between `validate` and `execute` or next child's iteration.

**Comment by polettix** [comment]
Trial release 2.003 seemed promising, so I decided to release 2.004. Thanks for your report!
